// Generated by https://quicktype.io

import { Distribution } from "./index";

export interface DistributionsResponse {
  uri?:         string | null;
  type?:        string | null;
  status?:      string | null;
  code?:        number | null;
  success?:     boolean | null;
  data?:        DataResponse | null;
  errors?:      null | null;
  res_title?:   string | null;
  res_content?: string | null;
  base_url?:    string | null;
}

export interface DataResponse {
  items?: Distribution[] | null;
}

